import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Oswald } from "next/font/google";
import { ThemeToggle } from "./components/ThemeToggle/ThemeToggle";
import Navbar from "./components/NavBar/Navbar";
import Header from "./components/Header/Header"
import "./globals.css";


export const metadata: Metadata = {
  title: "A Coding Blog Website",
  description: "Generated by create next app",
};

const oswald = Oswald({
  subsets: ['cyrillic'],
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${oswald.className}`} suppressHydrationWarning>
      <body className="transition-colors duration-300 ease-in-out">
        {/* persists theme preferences across sessions */}
        <ThemeProvider
          attribute={"data-theme"}
          defaultTheme="myLightTheme"
          enableSystem
          themes={["myLightTheme", "myDarkTheme"]}
        >
          <Navbar />
          <Header />
          {children}
          <ThemeToggle />
        </ThemeProvider>
      </body>
    </html>
  );
}
