import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import { ThemeToggle } from "./components/ThemeToggle/ThemeToggle";
import Header from "./components/NavBar/Navbar";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const oswald = Oswald({
  subsets: ['cyrillic'],
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={oswald.className}>
      <body suppressHydrationWarning className="bg-[#EAEAEA] text-[#2E2B2C] transition-colors duration-300 ease-in-out">
        <Header />
        {children}
        <ThemeToggle />
      </body>
    </html>
  );
}
